name: $(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

on:
  push:
    branches:
      - main

jobs:
  TerraformPlan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize Terraform
      run: terraform init -input=false
      working-directory: terraform/
      
    - name: Validate Terraform Configuration
      run: terraform validate
      working-directory: terraform/
      
    - name: Plan Terraform Changes
      run: |
        terraform plan -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_TENANT_ID=$ARM_TENANT_ID" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID"
      working-directory: terraform/
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Apply Terraform Changes
      run: |
        terraform apply -auto-approve -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_TENANT_ID=$ARM_TENANT_ID" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -input=false
      working-directory: terraform/
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
